### ISSUE TITLE
No need for before and after each in `paper.spec.js` `rock.spec.js` and `scissors.spec.js`

### ISSUE THREAD

**Issue by asos-giovannip** [sharoonarif/rock-paper-scissors-vue#1]
No need for empty before and after each in `paper.spec.js` `rock.spec.js` and `scissors.spec.js`

Remove:

```
beforeEach(() => {
});

afterEach(() => {
});
```

https://github.com/sharoonarif/rock-paper-scissors-vue/blob/56cc15b035129d0a1afb513ee71616e8da65149f/tests/moves/paper.spec.js#L4

https://github.com/sharoonarif/rock-paper-scissors-vue/blob/56cc15b035129d0a1afb513ee71616e8da65149f/tests/moves/rock.spec.js#L4

https://github.com/sharoonarif/rock-paper-scissors-vue/blob/56cc15b035129d0a1afb513ee71616e8da65149f/tests/moves/scissors.spec.js#L4

**Comment by sharoonarif** [comment]
Do one
